name: deploy

on:
  push:
    tags:
    - '*'

jobs:
  Deploy:
    name: Deploy
    runs-on: macOS-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Dependencies
        env:
            GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            set -o pipefail
            carthage version
            carthage bootstrap --use-xcframeworks

      - name: Generate Docs
        run: ./CI/publish-docs.sh

      - name: Publish Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

      - name: Build Carthage Binary
        run: |
            ./CI/publish-carthage.sh;
      - name: Upload Carthage Binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VirgilSDKE3Kit.xcframework.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Publish Cocoapods
        run: ./CI/publish-cocoapods.sh
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

