name: tests

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'
  pull_request:
    branches:
      - '**'

jobs:
  Tests:
    name: Tests (${{ matrix.platform }})
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - destination: "platform=iOS Simulator,name=iPhone 16,arch=arm64"
            platform: "iOS"
            test: "1"
          - destination: "platform=macOS,arch=x86_64"
            platform: "macOS"
            test: "1"
          - destination: "platform=tvOS Simulator,name=Apple TV 4K (3rd generation),arch=arm64"
            platform: "tvOS"
            test: "1"
          - destination: "platform=watchOS Simulator,name=Apple Watch Series 10 (46mm),arch=arm64"
            platform: "watchOS"
            test: "0"
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt tests config
        env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
        run: ./CI/decrypt-config.sh

      - name: Run ${{ matrix.platform }} Tests
        uses: nick-fields/retry@v2
        with:
          max_attempts: 20
          timeout_minutes: 30
          retry_on: error
          command: |
            if [ "${{ matrix.test }}" == "1" ]; then
                xcodebuild -scheme VirgilE3Kit -destination "${{ matrix.destination }}" -configuration Debug test | xcpretty;
            else
                xcodebuild -scheme VirgilE3Kit -destination "${{ matrix.destination }}" -configuration Release clean build | xcpretty;
            fi

  SPM:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt tests config
        run: ./CI/decrypt-config.sh
        env:
            ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
            ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
      - name: SPM test
        run: |
            brew install coreutils
            swift --version
            timeout 15m bash -c 'until swift build; do rm -fr .build && sleep 10; done'
            swift test

  Swiftlint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Swiftlint
        run: |
            brew install swiftlint
            swiftlint
